language: java
dist: xenial

addons:
  apt:
    sources:
      - sourceline: 'ppa:linux-rdma/rdma-core-daily'
    packages:
      - libibverbs-dev
      - librdmacm-dev

stages:
  - name: build
  - name: snapshot
    if: branch = master AND type = push

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: snapshot
      script: ./gradlew publish -Dgpr.user=${GPR_USER} -Dgpr.token=${GPR_TOKEN}