language: java
dist: xenial

addons:
  apt:
    sources:
      - sourceline: 'ppa:linux-rdma/rdma-core-daily'
    packages:
      - libibverbs-dev
      - librdmacm-dev

stages:
  - name: build
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: release
      script: ./gradlew publish -Dgpr.user=${GPR_USER} -Dgpr.token=${GPR_TOKEN} -Drelease=true
