logging:
  level:
    root: ERROR
    de.hhu.bsinfo: DEBUG

infiniband:

  device:
    deviceNumber: 0
    portNumber: 1

  network:
    queuePairSize: 128
    sharedReceiveQueueSize: 12800
    completionQueueSize: 12800
    maxScatterGatherElements: 1