logging:
  level:
    root: ERROR
    de.hhu.bsinfo: INFO

infiniband:

  device:
    deviceNumber: 0
    portNumber: 1

  network:
    queuePairSize: 32
    sharedReceiveQueueSize: 2048
    completionQueueSize: 2048
    maxScatterGatherElements: 4