logging:
  level:
    root: ERROR
    de.hhu.bsinfo: INFO

infiniband:

  device:
    deviceNumber: 0
    portNumber: 1

  network:
    queuePairSize: 20
    sharedReceiveQueueSize: 20
    completionQueueSize: 20
    maxScatterGatherElements: 4